feat: Move to using for_each for resource blocks
terraform-aws-modules/terraform-aws-security-group pull request #326
Opened 2024-08-29 07:58 UTC by pincher95

## Description
Move the security groups rules resource blocks to using the for_each meta-argument from the count.

## Motivation and Context
It is pretty widely understood that using the count meta-argument can cause churn ([ref](https://www.terraform.io/language/meta-arguments/count#when-to-use-for_each-instead-of-count)) in some contexts, such as the context in which this module is used.

## Breaking Changes
This change will break all security group rules resources based on count. It will cause churn when switching from an old count-based version of the module to a for_each-based version, because the resources are switching from being an ordered list (sg_rule[0], sg_rule[1], etc.) to a map (sg_rule["443-443-tcp"], sg_rule["22-22-tcp"], etc.).

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects
`# module.security_group.aws_security_group_rule.ingress_with_cidr_blocks["443-443-tcp"] will be created
  + resource "aws_security_group_rule" "ingress_with_cidr_blocks" {
      + cidr_blocks              = [
          + "10.10.0.0/16",
        ]
      + description              = "HTTPS"
      + from_port                = 443
      + id                       = (known after apply)
      + ipv6_cidr_blocks         = []
      + prefix_list_ids          = []
      + protocol                 = "tcp"
      + security_group_id        = (known after apply)
      + security_group_rule_id   = (known after apply)
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = 443
      + type                     = "ingress"
    }`
- [x] I have executed `pre-commit run -a` on my pull request

2024-09-02 09:57 UTC, pincher95 commented
@antonbabenko @bryantbiggs 
Can you please check this PR.

Thank you

2024-09-05 13:41 UTC, bryantbiggs commented
I think if we are going to do a breaking change on this module, we should evaluate all potential changes in order to minimize the amount of disruption. For example, I would hope in the next breaking change we would drop the use of `aws_security_group_rule` and replace it with `aws_vpc_security_group_ingress_rule`/ `aws_vpc_security_group_egress_rule`

2024-09-05 13:46 UTC, bryantbiggs requested changes
just an initial glance - if we are going to do this, we should re-evaluate it from a first principles approach, not just for the sake of changing from `count` to `for_each`

2024-09-05 13:46 UTC, bryantbiggs commented on main.tf
> +  for_each = local.create ? toset(var.ingress_rules) : toset([])
we cannot use `toset()` in this manner because it will inevitably cause conflicts down the road with computed values as keys

2024-09-05 13:46 UTC, bryantbiggs commented on main.tf
>  resource "aws_security_group_rule" "ingress_rules" {
this should be 
```suggestion
resource "aws_vpc_security_group_ingress_rule" "this" {
```

2024-09-05 13:46 UTC, bryantbiggs commented on main.tf
>  resource "aws_security_group_rule" "ingress_with_source_security_group_id" {
all of these can go away to one generic ingress rule resource and one generic egress rule resource

2024-09-05 13:46 UTC, bryantbiggs commented on main.tf
>  resource "aws_security_group_rule" "ingress_with_cidr_blocks" {
drop

2024-09-05 13:46 UTC, bryantbiggs commented on main.tf
>  resource "aws_security_group_rule" "ingress_with_self" {
drop

2024-09-05 13:46 UTC, bryantbiggs commented on main.tf
>  resource "aws_security_group_rule" "ingress_with_prefix_list_ids" {
drop

2024-09-05 13:46 UTC, bryantbiggs commented on main.tf
>  resource "aws_security_group_rule" "egress_rules" {
```suggestion
resource "aws_vpc_security_group_egress_rule" "this" {
```

2024-09-05 13:46 UTC, bryantbiggs commented on main.tf
> +  for_each = local.create ? toset(var.ingress_rules) : toset([])
no `toset()`

2024-09-05 13:46 UTC, bryantbiggs commented on main.tf
>  resource "aws_security_group_rule" "egress_with_cidr_blocks" {
drop

2024-09-05 13:46 UTC, bryantbiggs commented on main.tf
>  resource "aws_security_group_rule" "egress_with_self" {
drop

2024-09-05 13:46 UTC, bryantbiggs commented on main.tf
>  resource "aws_security_group_rule" "egress_with_prefix_list_ids" {
drop

2024-10-17 00:09 UTC, closed without merging